stages:
  - build
  - test

image: node:20-alpine

services:
  - name: docker:24-dind
    alias: docker

variables:
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache docker-cli docker-cli-compose

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always


build-app:
  stage: build
  script:
    - docker-compose build app
    - docker-compose images


test-app:
  stage: test
  script:
    - docker-compose up -d mongo
    - docker-compose run --rm app npm run test
