stages:
  - build
  - test
  - pull

image: docker:24.0

services:
  - name: docker:24.0-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache nodejs npm

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always


.build-app:
  stage: build
  script:
    - docker-compose build app
    - docker images

  artifacts:
    expire_in: 1h
    paths:
      - .

.test-app:
  stage: test
  image: node:20
  services:
    - name: docker:24.0-dind
      alias: docker

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  
  before_script:
    - apt-get update && apt-get install -y docker-compose

  script:
    - docker-compose up -d mongo
    - docker-compose run --rm app npm run test

pull-image:
  stage: pull
  before_script:
  - echo $container_registry_token | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY_IMAGE"
