
services:
  app:
    build: .
    container_name: qatu-api
    ports:
      - "3000:3000"
    environment:
      - CONNECTION_STRING=mongodb://mongo:27017/my_db
    
    depends_on:
      - mongo
    
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
    
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data: