
services:
  app:
    build: .
    container_name: qatu-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CONNECTION_STRING: mongodb://mongo:27017/my_db
      JWT_SECRET: "my_secret"
      CLIENT_URL: "*"
      NODE_ENV: http://localhost:5173
    
    depends_on:
      - mongo
    
    networks:
      - app-network

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
    
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data: