
services:
  app:
    image: ${APP_IMAGE}
    container_name: qatu-api
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      CONNECTION_STRING: ${CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      NODE_ENV: ${NODE_ENV}
    
    depends_on:
      - mongo
    
    networks:
      - back-end

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
    
    networks:
      - back-end

networks:
  back-end:

volumes:
  mongo-data:
